#pragma once

#include <stdint.h>

#define ICON_WIDTH 56
#define ICON_HEIGHT 44
#define ICON_OFFSET_X 12
#define ICON_OFFSET_Y 2
#define ICON_BITS_PER_PIXEL 2
#define ICON_BYTES ((ICON_WIDTH * ICON_HEIGHT * ICON_BITS_PER_PIXEL + 7) / 8)

/* Generated by tools/generate-icons.ps1. */

#define DECLARE_ICON(name) \
    extern const uint8_t icon_##name##_normal[ICON_BYTES]; \
    extern const uint8_t icon_##name##_active[ICON_BYTES]

DECLARE_ICON(landing_gear);
DECLARE_ICON(supercruise_decelerate);
DECLARE_ICON(hyperspace);
DECLARE_ICON(ship_lights);
DECLARE_ICON(silent_running);
DECLARE_ICON(night_vision);
DECLARE_ICON(hardpoints);
DECLARE_ICON(next_firegroup);
DECLARE_ICON(target);
DECLARE_ICON(target_next);
DECLARE_ICON(analysis_mode);
DECLARE_ICON(fss);
DECLARE_ICON(shield_power);
DECLARE_ICON(engine_power);
DECLARE_ICON(weapon_power);
DECLARE_ICON(balance_power);
DECLARE_ICON(cargo_scoop);
DECLARE_ICON(eject_cargo);
DECLARE_ICON(exploration);
DECLARE_ICON(comms_panel);
DECLARE_ICON(nav_panel);
DECLARE_ICON(trade);
DECLARE_ICON(galaxy_map);
DECLARE_ICON(system_map);

#undef DECLARE_ICON
